# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TrackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='items',
            field=models.ManyToManyField(to='tracks.TrackItem'),
        ),
    ]
