# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyset',
            name='answers',
        ),
        migrations.AddField(
            model_name='surveyset',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Answer'),
        ),
    ]
