# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_auto_20160213_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyset',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Answer'),
        ),
    ]
