# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_auto_20160213_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('survey', 'text')]),
        ),
    ]
