# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0009_auto_20160213_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='short_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
