# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
